'''
Title: EECS 348 Assignment 1
Description: CEO Email prioritization program
Input(s): Assignment1_Test_Files.txt
Output(s): Next email and number of unread emails
All collaborators: Geeks for geeks, ChatGPT, Gemini
Author's name: Edbert Jensen
Creation Date: 8/22/2025
'''

'''
Sources:
- https://www.geeksforgeeks.org/dsa/introduction-to-max-heap-data-structure/

'''
import os
import re
from dataclasses import dataclass

# Generated by Gemini
# It's good practice to use a dataclass for structured data
@dataclass(order=True)
class Email:
    priority: int
    # We add a unique sequence number to handle tie-breaks correctly
    sequence: int
    details: tuple

class MaxHeap:
    def __init__(self):
        self.arr = []       # initialize an empty list when MaxHeap object is created
    
    # i should just be a variable that is the position or index the newly inserted node.
    # this fix was with the help of chatGPT. I initially had i as a parameter of MaxHeap and realized that i was suppose to be a temp variable.
    def heapify_up(self, i):
        # the definition of the parent property of Binary Heaps is (index - 1) floor division by 2
        parent = (i - 1) // 2   

        # A condition that checks if the parent is positie and whatever index i is bigger than the parent value
        if parent >= 0 and self.arr[i] > self.arr[parent]:       
            self.arr[i], self.arr[parent] = self.arr[parent], self.arr[i]

            # Recursively heapify the parent node
            self.heapify_up(parent)
    
    # i should be the current index 
    def heapify_down(self, i):
        largest = i
        left = 2 * i + 1
        right = 2 * i + 2
        
        # condition to fulfill: left child should be lesser than the size of the array and it should be larger than its parent
        if ( left < len(self.arr) ) and ( self.arr[left] > self.arr[largest] ):
        # swap the largest index to be the left index
            largest = left
        
        # 
        if ( right < len(self.arr) ) and ( self.arr[right] > self.arr[largest] ):
            largest = right
        
        if (largest != i):
            self.arr[i],self.arr[largest]=self.arr[largest],self.arr[i]

            #Recursively heapify the affected sub-tree
            self.heapify_down( largest )

    def insertNode(self,key):
        # Insert element to the list
        self.arr.append(key)
        
        # Heapify the new node following a Bottom-up approach
        self.heapify_up( len(self.arr) - 1 )   

    def deleteRoot(self):
        # bug: did not actually delete a space in the list
        # Generated by Gemini
        if not self.arr:
            return None
        
        arr_len = len(self.arr)
        # record root before deletion
        root = self.arr[0]

        # check if the heap is not empty after popping
        if self.arr:
            # Replace root with the last element and pop the last element
            self.arr[0] = self.arr.pop()
            # Heapify down from the new root
            self.heapify_down(0)

        # A return is not needed for the variable root because we have the peek function for that
    
    def peek(self):
        return self.arr[0] if self.arr else None
    
    # use this for printing the current count of how many unread emails ahead 
    def __len__(self):
        return len(self.arr)

    
'''
Sources: 
- https://www.geeksforgeeks.org/dsa/priority-queue-set-1-introduction/
- 

'''
# Priority Queue: a type of queue that arranges based on a priority values
class PriorityQueue:
    def __init__(self):
        self.heap = MaxHeap()

    # a method to insert a key to the Binary MaxHeap
    def enqueue(self, key):
        # insert a new element to the Queue
        self.heap.insertNode(key)
    
    def dequeue(self):
        # return the highest priority element which is the root of a Binary Max Heap and heapify down the Binary Max Heap
        root = self.heap.peek()
        if root != None:
            return root
        self.heap.deleteRoot()
        
    
    # generated by Gemini
    def is_empty(self):
        return len(self.heap) == 0

    def peek(self):
        return self.heap.peek()
    
    def get_count(self):
        return len(self.heap)
    
    # --- PRINTER FUNCTION FOR DEBUGGING ---
    # This is the Pythonic way to create a "printer" for an object.
    # When you call print(your_queue_object), this method will be used.
    def __repr__(self):
        if self.is_empty():
            return "PriorityQueue: [ (empty) ]"
        
        # This will show the contents of the heap clearly
        items = [f"(Prio: {email.priority}, To: {email.details[0]})" for email in self.heap.arr]
        return f"PriorityQueue: [\n  " + ",\n  ".join(items) + "\n]"
    

# Driver class
class Driver:
    def __init__(self):
        self.queue = PriorityQueue()
        self.email_sequence = 0 # Counter to ensure FIFO for same-priority emails

    def readFile(self, fileName):
        try:
            with open(fileName, "r", encoding="utf-8") as f: 
                lines = f.readlines()
            return lines
        except FileNotFoundError:
            print(f"Error: The file '{fileName}' was not found.")
            return None # Return None to indicate failure
         
    # load file contents and parse accordingly
    def loadAndParse(self, fileContents):
        # check if file contents are there 
        # generated by Gemini.
        if fileContents is None:
            print("Cannot process file because it could not be read.")
            return
        
        # for-loop to access singular content lines when iterating
        for content in fileContents:
            # remove newline in the content
            cleanedLine = content.strip()
            if not cleanedLine:  # Skip empty lines
                continue
            # split the space to access commands
            parts = cleanedLine.split(' ',1) 
            # take the first element of parts as the command
            command = parts[0]

            # check commands 
            if command == "EMAIL":
                if len(parts) < 2:
                    print(f"Skipping malformed EMAIL line (no arguments): {cleanedLine}")
                    continue                    
    
                # I will use integers from 1-5 , 5 being the highest priority and 1 being the least.
                # when split is used in a list, it will not make another list inside the list
                details = parts[1].split(',')
                sender = details[0]
                
                priority_val = 1  # Default priority for "Other"
                match sender:
                    case "Boss":
                        priority_val = 5
                    case "Subordinate":
                        priority_val = 4
                    case "Peer":
                        priority_val = 3
                    case "ImportantPerson":
                        priority_val = 2

                email_data = Email(priority=priority_val, sequence=self.email_sequence, details=tuple(details))
                self.queue.enqueue(email_data)
                self.email_sequence += 1  # Increment sequence for next email
                
                # --- USING THE PRINTER FOR DEBUGGING ---
                print(f"ACTION: Added email from {sender}. Queue state:")
                print(self.queue)
                print("-" * 20)

            # dequeue operation should be handled here
            elif command == "NEXT":
                if self.queue.is_empty():
                    print("No unread emails.")
                    continue
                
                next_email = self.queue.peek()
                if next_email:
                    print(f"Next email:\n Sender: {next_email.details[1]}, Subject: {next_email.details[2]}, Priority: {next_email.priority}")
            
            # display the current count of unread emails
            elif command == "COUNT":
                pass
            
            # function that signals email has been read and dealt with
            elif command == "READ":
                self.queue.dequeue()

    
            else:
                continue
            

        
    

if __name__ == '__main__':

    defaultboolval = True

    while defaultboolval != False:
        
        test = input("Insert Test file Name: ")
        x = re.findall(".txt", test)
        if x:
            if isinstance(x[0], str) and x[0] == ".txt":
                # all creation of driver object and calls are made here
                driver = Driver()

                contents = driver.readFile(test)

                if contents:
                    driver.loadAndParse(contents)

                defaultboolval = False
        else:
            print("Invalid input. Please provide a file name ending with .txt")
            defaultboolval = True
    

    

    
        